version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - ./.env-settings
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      # MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: soat_order_db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: password123
    #   MONGO_INITDB_DATABASE: soat_order_db
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'
    restart: always

  mongodb-express:
    image: mongo-express
    container_name: mongodb-express
    # env_file:
    #   - ./.env-settings
    restart: always
    ports:
      - 8081:8081
    links:
      - mongodb
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      # ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      # ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/

volumes:
  mongo:


# version: '3.1'
# services:
#   mongodb:
#     image: mongo:latest
#     restart: always
#     container_name: mongodb
#     env_file:
#       - ./.env-settings
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
#       MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
#     volumes:
#       - mongo:/data/db
#     ports:
#       - '6000:27017'

  # mongodb-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   links:
  #     - mongodb
  #   env_file:
  #     - ./.env-settings
  #   environment:
  #     ME_CONFIG_BASICAUTH_USERNAME: admin
  #     ME_CONFIG_BASICAUTH_PASSWORD: admin
  #     ME_CONFIG_MONGODB_PORT: 27017
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password123
  #     ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/      

# volumes:
#   mongo:
