version: '3'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - ./.env-settings
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: soat_order_db
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'
    restart: always

  mongodb-express:
    image: mongo-express
    container_name: mongodb-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongodb
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/

  soat-order:
    build: ./
    image: soat-order/python:23.07    
    container_name: soat-order
    restart: always
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    working_dir: /app
    ports:
      - 8000:8000
    links:
      - mongodb
    depends_on:
      - mongodb  
    volumes:
      - "./app:/app"
      - "./requirements.txt:/app/requirements.txt"
      - "$PWD/.env-prd:/app/.env-settings"
    tty: true  
    command: >
      bash -c "python -u main.py
      && /bin/bash"

volumes:
  mongo:
