version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - ../app/.env-settings
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    #   MONGO_INITDB_DATABASE: soat_order_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: soat_order_db
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'
    restart: always


  mongodb-express:
    image: mongo-express
    container_name: mongodb-express
    # env_file:
    #   - ./app/.env-settings
    restart: always
    ports:
      - 8081:8081
    links:
      - mongodb
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      # ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      # ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      # ME_CONFIG_MONGODB_URL: ${DB_DATABASE_URL}


  localstack:
    container_name: localstack
    hostname: sqs
    image: localstack/localstack:latest
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=sa-east-1
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=soat-order
      - AWS_SECRET_ACCESS_KEY=soat-order
      - DEBUG=1
      - PORT_WEB_UI=${PORT_WEB_UI-}
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-9000}:${PORT_WEB_UI-8080}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      # - $HOME/.aws:/root/.aws:ro
      # - ./credentials:/root/.aws/credentials:ro
      - ./localstack_bootstrap.sh:/etc/localstack/init/ready.d/init-aws.sh


volumes:
  mongo:

